//#define CLOCK_TRIM_HOURS

#define EFFECT_SPEED 200000
#define EFFECT_SLOT_MACHINE
//#define EFFECT_TRANSITION

#define ANTI_POISON_DELAY 200

#ifdef EFFECT_SLOT_MACHINE
#define EFFECT_ENABLED
#endif
#ifdef EFFECT_TRANSITION
#define EFFECT_ENABLED
#endif
