//#define CLOCK_TRIM_HOURS

#define EFFECT_SPEED 200000
#define EFFECT_SLOT_MACHINE
//#define EFFECT_TRANSITION

#define ANTI_POISON_DELAY 200

#define DISPLAY_RENDER_PERIOD 2000
#define DISPLAY_BLANK_PERIOD 200

#ifdef EFFECT_SLOT_MACHINE
#define EFFECT_ENABLED
#endif
#ifdef EFFECT_TRANSITION
#define EFFECT_ENABLED
#endif
