#pragma once

//#define CLOCK_TRIM_HOURS
#define EFFECT_SPEED 200000UL
#define ANTI_POISON_DELAY 200000UL
#define DISPLAY_RENDER_STEP 20

#define HOST_SERIAL Serial
#define WIFI_SERIAL Serial3

#undef ENABLE_ESPPROXY
